/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 monad-billboard.glb --transform -s -S -k 
Files: monad-billboard.glb [900.48KB] > /Users/stephen/Downloads/monad-billboard-transformed.glb [30.93KB] (97%)
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const { nodes, materials } = useGLTF(
    "/models/monad-billboard-transformed.glb"
  ) as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Billboard_Billboard_Mat_1_0"
        castShadow
        receiveShadow
        geometry={nodes.Billboard_Billboard_Mat_1_0.geometry}
        material={materials.Billboard_Mat_1}
        position={[0, 0.019, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.014}
      />
      <mesh
        name="Billboard_Billboard_Mat_2_0"
        castShadow
        receiveShadow
        geometry={nodes.Billboard_Billboard_Mat_2_0.geometry}
        material={materials.Billboard_Mat_2}
        position={[0, 0.019, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.014}
      />
      <mesh
        name="Billboard_Billboard_Texture_0"
        castShadow
        receiveShadow
        geometry={nodes.Billboard_Billboard_Texture_0.geometry}
        material={materials.Billboard_Texture}
        position={[0, 0.019, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.014}
      ></mesh>
    </group>
  );
}

useGLTF.preload("/models/monad-billboard-transformed.glb");
