/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 monad.glb --transform -s -S -k 
Files: monad.glb [11.17MB] > /Users/stephen/Downloads/monad-transformed.glb [1.79MB] (84%)
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const { nodes, materials } = useGLTF("/models/monad-transformed.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Object_10"
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_15"
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.Disk_Tormoza}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_17"
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Fari_szadi_steclo}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_18"
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_2"
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Fara_steclo_speredi}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_3"
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_32"
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.PaletteMaterial004}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_34"
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.Rezina}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_40"
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.PaletteMaterial005}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_41"
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials.Steclo_povoroti}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_44"
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.PaletteMaterial006}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_6"
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.PaletteMaterial007}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
      <mesh
        name="Object_7"
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Speedometr}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.007}
      />
    </group>
  );
}

useGLTF.preload("/models/monad-transformed.glb");
